name: fcl
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.17.0 # date formater
  auto_route_generator: ^2.1.0 #routes generation
  provider: ^5.0.0 #for state management
  http: ^0.13.3 #for http requests
  shared_preferences: ^2.0.6  #persistent storage for simple data
  flutter:
    sdk: flutter
  
  #Misc.
  flutter_gifimage: ^1.0.1
  font_awesome_flutter: ^9.0.0
  carousel_slider: ^3.0.0

  device_info: ^2.0.2 #to get info of devicw
  package_info: ^2.0.2  #to get build info
  flutter_launcher_icons: ^0.9.0 #for launcher icons
  pin_code_text_field: ^1.8.0 #for verification code ui
  webview_flutter: ^2.0.8 #for webview in flutter
  fluttertoast: ^8.0.7 #show toast
  flutter_svg: ^0.22.0
  image_pixels: ^1.0.2 #for pixels
  intro_slider: ^2.3.3 #introduction-screens
  image_picker: ^0.6.0+9  #image picker
  connectivity: ^3.0.6 #for internet connectivity
  pull_to_refresh: ^1.6.1 #for drop down refersh and pull up load
  country_code_picker: ^1.4.0 # for country code with flags
  url_launcher: ^6.0.6 #for url launch to browser
  email_launcher: ^1.0.0 #for email launcher
  url_launcher_platform_interface: ^2.0.3
  plugin_platform_interface: ^2.0.0
  firebase_core_platform_interface: ^4.0.1
  # flutter_local_notifications: ^1.4.4+4
  firebase_analytics: ^8.1.2
  get: #for get dependency anager
  firebase_core: ^1.3.0 #to use firebase functionalities
  firebase_messaging: ^10.0.1 #to use firebase cloud messaging
  flutter_local_notifications: ^5.0.0
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "Launcher_icon"
  ios: true
  image_path: "assets/images/fcl_launch_icon.png"  
  # image_path: "assets/images/FCL Launcher Icon.jpg"    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family:  CustomIcons
  #     fonts:
  #      - asset: assets/icons/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
